control_type = 'gamepad_direct'

[direct_motors]
motor_ports = ["A", "D"]
[direct_motors.motors]
[direct_motors.motors.A]
    type      = "tank"
    partner   = "D"
    side      = "right"
    max_power = 40
    max_speed = 40
    sign      = 1
    partner_sign = 1
